export const CAPABILITY = {
  profileRead: 'profile.read',
  sessionsManage: 'sessions.manage',
  privacyOwn: 'privacy.own',
  notificationsRead: 'notifications.read',
  notificationsRegister: 'notifications.register',
  callsJoin: 'calls.join',
  heartbeatRead: 'heartbeat.read',
  modulesRead: 'modules.read',
  modulesRequest: 'modules.request',
  safetyPanic: 'safety.panic',
  remindersRead: 'reminders.read',
  remindersWrite: 'reminders.write',
  assistantVoice: 'assistant.voice',
  directoryRead: 'directory.read',
  peopleRead: 'people.read',
  peopleWrite: 'people.write',
  memoryManage: 'memory.manage',
  usersManage: 'users.manage',
  invitationsManage: 'invitations.manage',
  privacyHousehold: 'privacy.household',
  settingsManage: 'settings.manage',
  modulesManage: 'modules.manage',
  activityRead: 'activity.read',
  cameraView: 'camera.view',
  cameraTalk: 'camera.talk',
  cameraManage: 'camera.manage',
  zonesRead: 'zones.read',
  eventsRead: 'events.read',
  guardRead: 'guard.read',
  zonesWrite: 'zones.write',
  guardModeSet: 'guard.mode.set',
  guardGuestsWrite: 'guard.guests.write',
  safetyDuress: 'safety.duress',
  responseDuty: 'response.duty',
  safetyRead: 'safety.read',
  visitorsRead: 'visitors.read',
  guardAdmin: 'guard.admin',
  visitorsManage: 'visitors.manage',
  presenceRead: 'presence.read',
  agendaRead: 'agenda.read',
  agendaWrite: 'agenda.write',
  projectsRead: 'projects.read',
  projectsWrite: 'projects.write',
} as const;

export type Capability = (typeof CAPABILITY)[keyof typeof CAPABILITY];

export const CONTEXT_WAIT_MS = 3000;
