import {
  Activity,
  ArrowLeft,
  ArrowUpRight,
  Bell,
  CalendarDays,
  Camera,
  Check,
  CheckCircle2,
  Clock3,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Eye,
  Flashlight,
  Filter,
  FlashlightOff,
  Home,
  History,
  Keyboard,
  KeyRound,
  ListTodo,
  LoaderCircle,
  Link,
  MessagesSquare,
  MoreHorizontal,
  Mic,
  MicOff,
  Monitor,
  Pencil,
  Moon,
  PieChart,
  Plus,
  RefreshCw,
  LogOut,
  WifiOff,
  QrCode,
  ScanBarcode,
  ScanFace,
  Settings,
  SquarePen,
  Trash2,
  Search,
  ShieldCheck,
  SkipForward,
  SlidersHorizontal,
  Sparkles,
  Sun,
  TriangleAlert,
  TrendingDown,
  TrendingUp,
  Unlink,
  Shield,
  DoorOpen,
  Siren,
  UserCheck,
  PhoneOff,
  Hand,
  User,
  Users,
  UserMinus,
  UserPlus,
  Video,
  Volume2,
  Wifi,
  X,
} from 'lucide-react-native';

export const ICONS = {
  activity: Activity,
  'arrow-left': ArrowLeft,
  'arrow-up-right': ArrowUpRight,
  bell: Bell,
  calendar: CalendarDays,
  camera: Camera,
  'check-circle': CheckCircle2,
  clock: Clock3,
  flashlight: Flashlight,
  filter: Filter,
  'flashlight-off': FlashlightOff,
  home: Home,
  history: History,
  keyboard: Keyboard,
  'key-round': KeyRound,
  'list-todo': ListTodo,
  'loader-circle': LoaderCircle,
  link: Link,
  'messages-square': MessagesSquare,
  'more-horizontal': MoreHorizontal,
  mic: Mic,
  'mic-off': MicOff,
  monitor: Monitor,
  moon: Moon,
  'pie-chart': PieChart,
  plus: Plus,
  'refresh-cw': RefreshCw,
  'log-out': LogOut,
  'wifi-off': WifiOff,
  'qr-code': QrCode,
  'scan-barcode': ScanBarcode,
  'scan-face': ScanFace,
  settings: Settings,
  'square-pen': SquarePen,
  trash: Trash2,
  search: Search,
  'shield-check': ShieldCheck,
  'skip-forward': SkipForward,
  sliders: SlidersHorizontal,
  sparkles: Sparkles,
  sun: Sun,
  'triangle-alert': TriangleAlert,
  'trending-up': TrendingUp,
  unlink: Unlink,
  user: User,
  'user-minus': UserMinus,
  'user-plus': UserPlus,
  users: Users,
  video: Video,
  'volume-2': Volume2,
  wifi: Wifi,
  x: X,
  check: Check,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'chevron-up': ChevronUp,
  eye: Eye,
  pencil: Pencil,
  'trending-down': TrendingDown,
  shield: Shield,
  'door-open': DoorOpen,
  siren: Siren,
  'user-check': UserCheck,
  'phone-off': PhoneOff,
  hand: Hand,
} as const;
