import {
  Camera,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronRight,
  ChevronUp,
  KeyRound,
  Link,
  Mic,
  MicOff,
  Monitor,
  Moon,
  RefreshCw,
  ScanBarcode,
  ShieldCheck,
  Sparkles,
  Sun,
  Unlink,
  Video,
  X,
} from 'lucide-react-native';

export const ICONS = {
  camera: Camera,
  'check-circle': CheckCircle2,
  'key-round': KeyRound,
  link: Link,
  mic: Mic,
  'mic-off': MicOff,
  monitor: Monitor,
  moon: Moon,
  'refresh-cw': RefreshCw,
  'scan-barcode': ScanBarcode,
  'shield-check': ShieldCheck,
  sparkles: Sparkles,
  sun: Sun,
  unlink: Unlink,
  video: Video,
  x: X,
  check: Check,
  'chevron-down': ChevronDown,
  'chevron-right': ChevronRight,
  'chevron-up': ChevronUp,
} as const;
