import {
  ArrowRight,
  Camera,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Eye,
  Flashlight,
  Menu,
  Mic,
  MicOff,
  Pause,
  Play,
  Plus,
  RefreshCw,
  ScanFace,
  SkipForward,
  Sparkles,
  TriangleAlert,
  X,
} from 'lucide';

export const MORPH_ICONS = {
  'arrow-right': ArrowRight,
  camera: Camera,
  check: Check,
  'check-circle': CheckCircle2,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'chevron-up': ChevronUp,
  eye: Eye,
  flashlight: Flashlight,
  menu: Menu,
  mic: Mic,
  'mic-off': MicOff,
  pause: Pause,
  play: Play,
  plus: Plus,
  'refresh-cw': RefreshCw,
  'scan-face': ScanFace,
  'skip-forward': SkipForward,
  sparkles: Sparkles,
  'triangle-alert': TriangleAlert,
  x: X,
} as const;
